name: AndroidBox Dev
run-name: AndroidBox build
on:
  push:
    branches:         # array of glob patterns matching against refs/heads. Optional; defaults to all
      - dev          # triggers on pushes that contain changes in main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5.2.0
        with:
          go-version: 1.22
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d
      - name: Build the build tool
        run: 'pwd && go mod tidy && cd cmd/build && go build .'
      - name: check build config
        run: 'pwd && cat .github/config/dev.config.yaml'
      - name: Build AndroidBox
        run: 'pwd && cmd/build/build -f .github/config/dev.config.yaml'
            